version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    mem_limit: 8192m
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    mem_limit: "8192m"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  mongodb:
    image: mongo:latest
    ports: 
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
